language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
after_success:
- mvn -P coverall clean test jacoco:report coveralls:report
notifications:
  slack:
    secure: n39oJrjifD29rXE+MnP+7Ibx6HJijpOPtthFXiC5lqOzwqyeEab0PCXu21ScAQr7UKMdM+C5Crk2qQdbmBGAb08D+Vg1AOGy3rjudyYLKL3ZVD+Ri6v8MuVHaloKHla3cmSyuWdW3I+NPaAuRVXOsSxc/XHVcTx77Zt0v2RfVMqJzKIMqtPEdV7bqaELsEnd+XSa6D8ghQ2GYEm1yQoDTbl7EX+mFzO04WIRs8tPvmwoF4QPJLv7iIejkYp8nWBA6uVTbPipkiTFuuOf3lxyupsl+Yrq9ECOv204940NUgbjxVcKh6RfKNyOWky44bV3M62pwu7MBmFuoaFUBFbypsgnlSFbqMJjsq1dupP8+TPIUzdTdNaXzHeaHXF8GZzL5Lf1aWgYts1Ic9YFWgwAO49LAzOGXlzAp8KxIocZvopFo30mnhlGKDyBPMhXmY16QuatlncGxNc3eCPfbsjh8igEDrIiNTLdCD5SlSByCiLCzwjjVTeGQRFlcjdH3+w/RAENOcyUw0WDgkoc59ZIvk6/Rwl0opQNF6sYYQ3I42CHvMU+czVTtGW77FSP2AkbPAuQS+3CRNRQyM+mtrIsaEH73aeRIO5GWKSjXGpAXk1q0wbSbtpzWkhuazOyEFSxanhY6DAUVoIj4Xd/hxWgY5Oz3wtu1jacMeZmWxAsrFQ=
